package local.remoteandroid.direct;
import android.app.*;import android.os.*;import android.media.*;import android.view.*;import android.widget.*;import android.text.InputType;import android.util.Base64;import org.json.JSONObject;import java.io.*;import java.nio.*;import java.nio.charset.StandardCharsets;import java.security.*;import java.security.cert.*;import java.util.*;import javax.net.ssl.*;
/** Native scrcpy 4.1 client. The only input endpoint is Android's control socket. */
public class MainActivity extends Activity {
 final java.util.concurrent.atomic.AtomicLong receivedFrames=new java.util.concurrent.atomic.AtomicLong(),presentedFrames=new java.util.concurrent.atomic.AtomicLong();
 final Handler ui=new Handler(Looper.getMainLooper());final HandlerThread statsThread=new HandlerThread("render-stats");long lastMoveMs;volatile boolean hardwareVideo;TextView perf;
 final List<SSLSocket> sockets=Collections.synchronizedList(new ArrayList<>());volatile boolean running;volatile int width=720,height=1280,generation;volatile MediaCodec video,audio;volatile DataOutputStream control;SurfaceView screen;FrameLayout canvas;AudioTrack track;SSLContext tls;final List<byte[]> fingerprints=new ArrayList<>();String host,auth;TextView status;EditText address,user,password;final java.util.concurrent.ExecutorService input=java.util.concurrent.Executors.newSingleThreadExecutor();
 public void onCreate(Bundle b){super.onCreate(b);statsThread.start();updater=new AppUpdater(this);if(Build.VERSION.SDK_INT>=37&&checkSelfPermission("android.permission.ACCESS_LOCAL_NETWORK")!=0)requestPermissions(new String[]{"android.permission.ACCESS_LOCAL_NETWORK"},8);getWindow().addFlags(128);login();getWindow().getDecorView().post(()->{WindowInsetsController c=getWindow().getDecorView().getWindowInsetsController();if(c!=null)c.setSystemBarsAppearance(WindowInsetsController.APPEARANCE_LIGHT_STATUS_BARS|WindowInsetsController.APPEARANCE_LIGHT_NAVIGATION_BARS,WindowInsetsController.APPEARANCE_LIGHT_STATUS_BARS|WindowInsetsController.APPEARANCE_LIGHT_NAVIGATION_BARS);});}
 AppUpdater updater;
 int maxSize=1600;
 void login(){
  android.content.SharedPreferences saved=getSharedPreferences("connection",0);
  LinearLayout box=new LinearLayout(this);box.setOrientation(1);box.setPadding(CuteUi.dp(this,20),CuteUi.dp(this,16),CuteUi.dp(this,20),CuteUi.dp(this,16));box.setBackgroundColor(0xfff5fbf9);
  TextView title=new TextView(this);title.setText(getString(R.string.app_name)+"\n你的随身小安卓");title.setTextSize(21);title.setTextColor(CuteUi.INK);LinearLayout heading=new LinearLayout(this);heading.setGravity(Gravity.CENTER_VERTICAL);ImageView avatar=CuteUi.avatar(this);LinearLayout.LayoutParams avatarLayout=new LinearLayout.LayoutParams(CuteUi.dp(this,56),CuteUi.dp(this,56));avatarLayout.setMarginEnd(CuteUi.dp(this,10));heading.addView(avatar,avatarLayout);heading.addView(title,new LinearLayout.LayoutParams(0,-2,1));Button update=new Button(this);update.setText("检查更新 · v"+BuildConfig.VERSION_NAME);CuteUi.style(update,CuteUi.MINT,true);update.setOnClickListener(v->updater.check(true));heading.addView(update,new LinearLayout.LayoutParams(-2,CuteUi.dp(this,48)));box.addView(heading);
  address=field(box,"服务器 IP 或主机名（可带 :15556）",saved.getString("host","192.168.9.99"));address.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_URI);
  user=field(box,"直连用户名",saved.getString("username","wyw"));password=field(box,"直连密码（仅本次连接）","");password.setInputType(129);
  CheckBox reveal=new CheckBox(this);reveal.setText("显示密码，核对特殊符号");reveal.setOnCheckedChangeListener((button,checked)->{password.setTransformationMethod(checked?android.text.method.HideReturnsTransformationMethod.getInstance():android.text.method.PasswordTransformationMethod.getInstance());password.setSelection(password.length());});box.addView(reveal);
  TextView qualityLabel=new TextView(this);qualityLabel.setText("清晰度（下次连接生效）");box.addView(qualityLabel);
  Spinner quality=new Spinner(this);String[] labels={"流畅 · 432 × 960","540p · 540 × 1200","720p · 720 × 1600","1080p · 1080 × 2400"};int[] sizes={960,1200,1600,2400};
  ArrayAdapter<String> choices=new ArrayAdapter<>(this,android.R.layout.simple_spinner_item,labels);choices.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);quality.setAdapter(choices);
  int[] legacySizes={960,1600,2400};int remembered=saved.getInt("quality_max_size",legacySizes[Math.max(0,Math.min(2,saved.getInt("quality",1)))]);int selected=2;for(int i=0;i<sizes.length;i++)if(sizes[i]==remembered)selected=i;quality.setSelection(selected);box.addView(quality);
  Button start=new Button(this);start.setText("连接虚拟安卓");CuteUi.style(start,CuteUi.MINT,false);box.addView(start,new LinearLayout.LayoutParams(-1,CuteUi.dp(this,60)));status=new TextView(this);status.setText("记住地址、用户名和清晰度，密码不会保存。");box.addView(status);
  start.setOnClickListener(v->{
   try{host=Endpoint.host(address.getText().toString());}catch(IllegalArgumentException e){status.setText(e.getMessage());return;}
   address.setText(host);maxSize=sizes[quality.getSelectedItemPosition()];
   saved.edit().putString("host",host).putString("username",user.getText().toString()).putInt("quality_max_size",maxSize).apply();
   auth="Basic "+Base64.encodeToString((user.getText()+":"+password.getText()).getBytes(StandardCharsets.UTF_8),2);start.setEnabled(false);status.setText("连接中…");
   new Thread(()->{try{initTLS();String id=session();runOnUiThread(()->{password.setText("");show(id);});}catch(Exception e){auth=null;runOnUiThread(()->{status.setText("连接失败："+message(e));start.setEnabled(true);});}},"login").start();
  });
  ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);scroll.addView(box);
  scroll.setOnApplyWindowInsetsListener((v,insets)->{android.graphics.Insets i=insets.getInsets(WindowInsets.Type.systemBars());v.setPadding(i.left,i.top,i.right,i.bottom);return insets;});setContentView(scroll);updater.check(false);
 }
 EditText field(LinearLayout b,String hint,String value){EditText f=new EditText(this);f.setSingleLine();f.setTextColor(CuteUi.INK);f.setHintTextColor(0xff719095);f.setBackgroundTintList(android.content.res.ColorStateList.valueOf(0xffaacfc5));f.setHint(hint);f.setText(value);b.addView(f);return f;}
 static String message(Exception e){return e.getMessage()==null?e.getClass().getSimpleName():e.getMessage();}
 void initTLS()throws Exception{KeyStore ks=KeyStore.getInstance(KeyStore.getDefaultType());ks.load(null,null);fingerprints.clear();int[] resources={R.raw.server_cert,R.raw.server_cert_m5};for(int i=0;i<resources.length;i++){X509Certificate cert;try(InputStream in=getResources().openRawResource(resources[i])){cert=(X509Certificate)CertificateFactory.getInstance("X.509").generateCertificate(in);}fingerprints.add(MessageDigest.getInstance("SHA-256").digest(cert.getEncoded()));ks.setCertificateEntry("mac"+i,cert);}TrustManagerFactory tm=TrustManagerFactory.getInstance(TrustManagerFactory.getDefaultAlgorithm());tm.init(ks);tls=SSLContext.getInstance("TLS");tls.init(null,tm.getTrustManagers(),null);}
 SSLSocket connect()throws Exception{SSLSocket s=(SSLSocket)tls.getSocketFactory().createSocket();s.connect(new java.net.InetSocketAddress(host,15556),7000);s.setSoTimeout(15000);s.setTcpNoDelay(true);s.startHandshake();byte[] actual=MessageDigest.getInstance("SHA-256").digest(s.getSession().getPeerCertificates()[0].getEncoded());boolean trusted=false;for(byte[] pin:fingerprints)trusted|=MessageDigest.isEqual(actual,pin);if(!trusted){s.close();throw new IOException("Mac 证书不匹配");}sockets.add(s);return s;}
 int header(InputStream in)throws Exception{ByteArrayOutputStream b=new ByteArrayOutputStream();int state=0;while(b.size()<16384){int c=in.read();if(c<0)throw new EOFException();b.write(c);if(state==0&&c==13)state=1;else if(state==1&&c==10)state=2;else if(state==2&&c==13)state=3;else if(state==3&&c==10)break;else state=0;}return Integer.parseInt(b.toString("US-ASCII").split("\\r\\n")[0].split(" ")[1]);}
 String session()throws Exception{SSLSocket s=connect();s.setSoTimeout(150000);byte[] settings=("{\"max_size\":"+maxSize+"}").getBytes(StandardCharsets.UTF_8);OutputStream out=s.getOutputStream();out.write(("POST /session HTTP/1.1\r\nHost: "+host+"\r\nAuthorization: "+auth+"\r\nContent-Type: application/json\r\nContent-Length: "+settings.length+"\r\nConnection: close\r\n\r\n").getBytes(StandardCharsets.US_ASCII));out.write(settings);InputStream in=s.getInputStream();int code=header(in);if(code!=200){s.close();throw new IOException(code==401?"登录被拒绝：请点“显示密码”核对用户名和特殊符号":code==429?"登录尝试过多，请稍后重试":"服务启动失败（"+code+"）");}ByteArrayOutputStream b=new ByteArrayOutputStream();byte[] buf=new byte[1024];int n;while((n=in.read(buf))>0)b.write(buf,0,n);s.close();sockets.remove(s);return new JSONObject(b.toString("UTF-8")).getString("session");}
 SSLSocket stream(String id,String role)throws Exception{SSLSocket s=connect();s.getOutputStream().write(("CONNECT /stream/"+id+"/"+role+" HTTP/1.1\r\nHost: "+host+"\r\nAuthorization: "+auth+"\r\n\r\n").getBytes(StandardCharsets.US_ASCII));if(header(s.getInputStream())!=200)throw new IOException("通道连接失败："+role);s.setSoTimeout(0);return s;}
 void show(String id){running=true;int gen=++generation;LinearLayout root=new LinearLayout(this);root.setOrientation(1);root.setOnApplyWindowInsetsListener((v,insets)->{android.graphics.Insets i=insets.getInsets(WindowInsets.Type.systemBars());v.setPadding(i.left,i.top,i.right,i.bottom);return insets;});canvas=new FrameLayout(this);canvas.setBackgroundColor(0xff000000);root.addView(canvas,new LinearLayout.LayoutParams(-1,0,1));screen=new SurfaceView(this);canvas.addView(screen,new FrameLayout.LayoutParams(-1,-1,17));screen.setOnTouchListener((v,e)->{if(e.getActionMasked()==MotionEvent.ACTION_MOVE){long now=SystemClock.uptimeMillis();if(now-lastMoveMs<16)return true;lastMoveMs=now;}MotionEvent copy=MotionEvent.obtain(e);input.execute(()->{touch(copy);copy.recycle();});return true;});int[] codes={4,3,187};LinearLayout bar=CuteUi.controls(this,j->{if(j<3)input.execute(()->key(codes[j]));else{stop();login();}});root.addView(bar);perf=new TextView(this);perf.setTextColor(0xffffffff);perf.setBackgroundColor(0x99000000);perf.setTextSize(11);perf.setPadding(8,4,8,4);canvas.addView(perf,new FrameLayout.LayoutParams(-2,-2,Gravity.TOP|Gravity.START));setContentView(root);canvas.post(this::fit);receivedFrames.set(0);presentedFrames.set(0);stats(gen);new Thread(()->{try{SSLSocket vs=stream(id,"video"),as=stream(id,"audio"),cs=stream(id,"control");control=new DataOutputStream(new BufferedOutputStream(cs.getOutputStream(),8192));auth=null;new Thread(()->readAudio(as,gen),"audio").start();new Thread(()->{try{byte[] b=new byte[2048];while(running&&gen==generation&&cs.getInputStream().read(b)>=0){}}catch(Exception ignored){}},"control-replies").start();readVideo(vs,gen);}catch(Exception e){if(running&&gen==generation)fail(e);}},"video").start();}

 static boolean virtualCodec(String name){return name.startsWith("c2.goldfish.")||name.startsWith("OMX.google.goldfish.");}
 MediaCodec fastDecoder(MediaFormat format)throws Exception{
  MediaCodecInfo chosen=null;int score=-1;
  for(MediaCodecInfo info:new MediaCodecList(MediaCodecList.REGULAR_CODECS).getCodecInfos()){
   if(info.isEncoder()||info.isAlias()||!info.isHardwareAccelerated()||virtualCodec(info.getName()))continue;
   for(String type:info.getSupportedTypes())if(type.equalsIgnoreCase("video/avc")){
    try{MediaCodecInfo.CodecCapabilities cap=info.getCapabilitiesForType(type);MediaFormat basic=MediaFormat.createVideoFormat("video/avc",width,height);
     if(!cap.isFormatSupported(basic)||cap.isFeatureRequired(MediaCodecInfo.CodecCapabilities.FEATURE_SecurePlayback)||cap.isFeatureRequired(MediaCodecInfo.CodecCapabilities.FEATURE_TunneledPlayback))continue;
     int candidate=cap.isFeatureSupported(MediaCodecInfo.CodecCapabilities.FEATURE_LowLatency)?2:1;if(candidate>score){score=candidate;chosen=info;}
    }catch(Exception ignored){}
   }
  }
  // Emulator host codecs may advertise hardware support but fail on the first frame.
  // Physical-phone hardware codecs retain priority; use a real software codec only as fallback.
  if(chosen==null)for(MediaCodecInfo info:new MediaCodecList(MediaCodecList.REGULAR_CODECS).getCodecInfos()){
   if(info.isEncoder()||info.isAlias()||!info.isSoftwareOnly())continue;
   for(String type:info.getSupportedTypes())if(type.equalsIgnoreCase("video/avc")){chosen=info;break;}
   if(chosen!=null)break;
  }
  MediaCodec decoder=chosen==null?MediaCodec.createDecoderByType("video/avc"):MediaCodec.createByCodecName(chosen.getName());hardwareVideo=decoder.getCodecInfo().isHardwareAccelerated();return decoder;
 }
 void stats(int gen){final long[] previous={System.nanoTime(),0,0};ui.postDelayed(new Runnable(){public void run(){if(!running||gen!=generation)return;long now=System.nanoTime(),rx=receivedFrames.get(),shown=presentedFrames.get();double dt=(now-previous[0])/1e9;perf.setText(String.format(java.util.Locale.ROOT,"接收 %.0f · 显示 %.0f FPS\n%d×%d · %s",(rx-previous[1])/dt,(shown-previous[2])/dt,width,height,hardwareVideo?"硬件解码":"软件解码"));previous[0]=now;previous[1]=rx;previous[2]=shown;ui.postDelayed(this,1000);}},1000);}

 void fit(){if(canvas==null)return;int w=canvas.getWidth(),h=canvas.getHeight();if(w==0||h==0)return;float s=Math.min((float)w/width,(float)h/height);screen.setLayoutParams(new FrameLayout.LayoutParams(Math.round(width*s),Math.round(height*s),17));}
 void configure(int w,int h,int gen)throws Exception{width=w;height=h;runOnUiThread(this::fit);for(int i=0;i<100&&running&&!screen.getHolder().getSurface().isValid();i++)Thread.sleep(20);MediaCodec old=video;video=null;if(old!=null){old.stop();old.release();}MediaFormat f=MediaFormat.createVideoFormat("video/avc",w,h);f.setInteger(MediaFormat.KEY_LOW_LATENCY,1);MediaCodec d=fastDecoder(f);d.configure(f,screen.getHolder().getSurface(),null,0);d.start();video=d;d.setOnFrameRenderedListener((codec,pts,ns)->{if(running&&gen==generation&&video==d)presentedFrames.incrementAndGet();},new Handler(statsThread.getLooper()));new Thread(()->{MediaCodec.BufferInfo info=new MediaCodec.BufferInfo();try{while(running&&gen==generation&&video==d){int index=d.dequeueOutputBuffer(info,10000);if(index>=0)d.releaseOutputBuffer(index,true);}}catch(Exception e){if(running&&gen==generation&&video==d)fail(e);}},"video-render").start();}
 void readVideo(SSLSocket s,int gen)throws Exception{DataInputStream in=new DataInputStream(new BufferedInputStream(s.getInputStream(),65536));if(in.readInt()!=0x68323634)throw new IOException("不支持的视频编码");while(running&&gen==generation){int hi=in.readInt();if((hi&0x80000000)!=0){int w=in.readInt(),h=in.readInt();if(w<1||h<1||w>8192||h>8192)throw new IOException("无效画面尺寸");configure(w,h,gen);continue;}long pts=((long)hi<<32)|(in.readInt()&0xffffffffL);int size=in.readInt();if(size<0||size>8*1024*1024)throw new IOException("无效视频帧");byte[] b=new byte[size];in.readFully(b);if((pts&(1L<<62))==0)receivedFrames.incrementAndGet();MediaCodec d=video;if(d==null)throw new IOException("缺少画面尺寸");int index=-1;while(running&&gen==generation&&(index=d.dequeueInputBuffer(10000))<0){}if(index<0)break;ByteBuffer buffer=d.getInputBuffer(index);buffer.clear();buffer.put(b);d.queueInputBuffer(index,0,size,pts&((1L<<61)-1),(pts&(1L<<62))!=0?MediaCodec.BUFFER_FLAG_CODEC_CONFIG:0);}}
 void readAudio(SSLSocket s,int gen){try{DataInputStream in=new DataInputStream(new BufferedInputStream(s.getInputStream(),16384));int codec=in.readInt();if(codec==0||codec==1)return;if(codec!=0x00616163)throw new IOException("不支持的音频编码");while(running&&gen==generation){long pts=in.readLong();int size=in.readInt();if(size<0||size>1024*1024)throw new IOException("无效音频帧");byte[] data=new byte[size];in.readFully(data);if((pts&(1L<<62))!=0){MediaFormat f=MediaFormat.createAudioFormat("audio/mp4a-latm",48000,2);f.setByteBuffer("csd-0",ByteBuffer.wrap(data));MediaCodec d=MediaCodec.createDecoderByType("audio/mp4a-latm");d.configure(f,null,null,0);d.start();audio=d;int min=AudioTrack.getMinBufferSize(48000,12,2);track=new AudioTrack.Builder().setAudioFormat(new AudioFormat.Builder().setSampleRate(48000).setChannelMask(12).setEncoding(2).build()).setAudioAttributes(new AudioAttributes.Builder().setUsage(1).setContentType(3).build()).setTransferMode(1).setBufferSizeInBytes(Math.max(min,4096)).setPerformanceMode(1).build();track.play();new Thread(()->drainAudio(d,gen),"audio-render").start();continue;}MediaCodec d=audio;if(d==null)continue;int index=-1;while(running&&gen==generation&&(index=d.dequeueInputBuffer(10000))<0){}if(index<0)break;ByteBuffer buf=d.getInputBuffer(index);buf.clear();buf.put(data);d.queueInputBuffer(index,0,size,pts&((1L<<61)-1),0);}}catch(Exception e){if(running&&gen==generation)runOnUiThread(()->Toast.makeText(this,"音频暂不可用："+message(e),1).show());}}
 void drainAudio(MediaCodec d,int gen){try{MediaCodec.BufferInfo info=new MediaCodec.BufferInfo();while(running&&gen==generation&&audio==d){int index=d.dequeueOutputBuffer(info,10000);if(index>=0){ByteBuffer b=d.getOutputBuffer(index);b.position(info.offset);b.limit(info.offset+info.size);while(b.hasRemaining()&&running)track.write(b,b.remaining(),0);d.releaseOutputBuffer(index,false);}}}catch(Exception ignored){}}
 synchronized void touch(MotionEvent e){if(control==null||!running)return;try{int a=e.getActionMasked();if(a==2){for(int i=0;i<e.getPointerCount();i++)pointer(e,i,2);}else if(a==0||a==5)pointer(e,e.getActionIndex(),0);else if(a==1||a==6)pointer(e,e.getActionIndex(),1);else if(a==3){for(int i=0;i<e.getPointerCount();i++)pointer(e,i,1);}control.flush();}catch(Exception ex){fail(ex);}}
 void pointer(MotionEvent e,int i,int a)throws IOException{int x=Math.max(0,Math.min(width-1,Math.round(e.getX(i)*width/screen.getWidth()))),y=Math.max(0,Math.min(height-1,Math.round(e.getY(i)*height/screen.getHeight())));control.writeByte(2);control.writeByte(a);control.writeLong(e.getPointerId(i));control.writeInt(x);control.writeInt(y);control.writeShort(width);control.writeShort(height);control.writeShort(a==1?0:65535);control.writeInt(0);control.writeInt(0);}
 synchronized void key(int code){if(control==null)return;try{for(int a=0;a<2;a++){control.writeByte(0);control.writeByte(a);control.writeInt(code);control.writeInt(0);control.writeInt(0);}control.flush();}catch(Exception e){fail(e);}}
 void fail(Exception e){runOnUiThread(()->{if(!running)return;stop();login();status.setText("连接中断："+message(e));});}
 void stop(){running=false;generation++;control=null;auth=null;synchronized(sockets){for(SSLSocket s:sockets)try{s.close();}catch(Exception ignored){}sockets.clear();}MediaCodec v=video,a=audio;video=null;audio=null;for(MediaCodec d:new MediaCodec[]{v,a})if(d!=null)try{d.stop();d.release();}catch(Exception ignored){}if(track!=null){try{track.stop();track.release();}catch(Exception ignored){}track=null;}}
 public void onBackPressed(){if(running)input.execute(()->key(4));else super.onBackPressed();}
 protected void onResume(){super.onResume();if(updater!=null)updater.resumeInstall();}
 protected void onDestroy(){stop();input.shutdownNow();statsThread.quitSafely();super.onDestroy();}
}
