package local.remoteandroid.direct;
import android.app.*;import android.os.*;import android.media.*;import android.view.*;import android.widget.*;import android.text.InputType;import android.util.Base64;import org.json.JSONObject;import java.io.*;import java.nio.*;import java.nio.charset.StandardCharsets;import java.security.*;import java.security.cert.*;import java.util.*;import javax.net.ssl.*;
/** Native scrcpy 4.1 client. The only input endpoint is Android's control socket. */
public class MainActivity extends Activity {
 final java.util.concurrent.atomic.AtomicLong receivedFrames=new java.util.concurrent.atomic.AtomicLong(),presentedFrames=new java.util.concurrent.atomic.AtomicLong();
 final Handler ui=new Handler(Looper.getMainLooper());final HandlerThread statsThread=new HandlerThread("render-stats");long lastMoveMs;volatile boolean hardwareVideo;volatile long networkRttMs=-1;volatile PlaybackClock playback;TextView perf;
 final List<SSLSocket> sockets=Collections.synchronizedList(new ArrayList<>());volatile boolean running;volatile int width=720,height=1280,generation;volatile MediaCodec video,audio;volatile DataOutputStream control;SurfaceView screen;FrameLayout canvas;AudioTrack track;SSLContext tls;final List<byte[]> fingerprints=new ArrayList<>();String host,auth;TextView status;EditText address,user,password;final java.util.concurrent.ExecutorService input=java.util.concurrent.Executors.newSingleThreadExecutor();
 public void onCreate(Bundle b){super.onCreate(b);if(Build.VERSION.SDK_INT>=33)getOnBackInvokedDispatcher().registerOnBackInvokedCallback(android.window.OnBackInvokedDispatcher.PRIORITY_DEFAULT,this::handleBack);statsThread.start();updater=new AppUpdater(this);if(Build.VERSION.SDK_INT>=37&&checkSelfPermission("android.permission.ACCESS_LOCAL_NETWORK")!=android.content.pm.PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{"android.permission.ACCESS_LOCAL_NETWORK"},8);getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);login();getWindow().getDecorView().post(()->{WindowInsetsController c=getWindow().getDecorView().getWindowInsetsController();if(c!=null)c.setSystemBarsAppearance(WindowInsetsController.APPEARANCE_LIGHT_STATUS_BARS|WindowInsetsController.APPEARANCE_LIGHT_NAVIGATION_BARS,WindowInsetsController.APPEARANCE_LIGHT_STATUS_BARS|WindowInsetsController.APPEARANCE_LIGHT_NAVIGATION_BARS);});}
 AppUpdater updater;
 MediaTransfer transfer;
 PasswordStore passwordStore;
 int maxSize=1600,bitRate=2500000;String bitrateMode="CBR";Button metricsToggle;boolean metricsVisible;
 void login(){
  android.content.SharedPreferences saved=getSharedPreferences("connection",0);
  if(!saved.getBoolean("nps_defaults_v1",false)){android.content.SharedPreferences.Editor edit=saved.edit();String previous=saved.getString("host","");if(previous.isEmpty()||previous.matches("192\\.168\\.9\\.(8|99|125|126)(:15556)?"))edit.putString("host","146.56.249.175:15556");String previousUser=saved.getString("username","");if(previousUser.isEmpty()||previousUser.equals("wyw"))edit.putString("username","huoguo");edit.putBoolean("nps_defaults_v1",true).apply();}
  passwordStore=new PasswordStore(this);
  LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(CuteUi.dp(this,20),CuteUi.dp(this,16),CuteUi.dp(this,20),CuteUi.dp(this,16));box.setBackgroundColor(0xfff5fbf9);
  TextView title=new TextView(this);title.setText(getString(R.string.app_name)+"\n你的随身小安卓");title.setTextSize(21);title.setTextColor(CuteUi.INK);LinearLayout heading=new LinearLayout(this);heading.setGravity(Gravity.CENTER_VERTICAL);ImageView avatar=CuteUi.avatar(this);LinearLayout.LayoutParams avatarLayout=new LinearLayout.LayoutParams(CuteUi.dp(this,56),CuteUi.dp(this,56));avatarLayout.setMarginEnd(CuteUi.dp(this,10));heading.addView(avatar,avatarLayout);heading.addView(title,new LinearLayout.LayoutParams(0,-2,1));Button update=new Button(this);update.setText("检查更新 · v"+BuildConfig.VERSION_NAME);CuteUi.style(update,CuteUi.MINT,true);update.setOnClickListener(v->updater.check(true));heading.addView(update,new LinearLayout.LayoutParams(-2,CuteUi.dp(this,48)));box.addView(heading);
  address=field(box,"服务器 IP 或主机名（可带 :15556）",saved.getString("host","146.56.249.175:15556"));address.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_URI);
  user=field(box,"直连用户名",saved.getString("username","huoguo"));password=field(box,"直连密码（可在本机加密保存）","");password.setInputType(129);
  CheckBox reveal=new CheckBox(this);reveal.setText("显示密码，核对特殊符号");reveal.setOnCheckedChangeListener((button,checked)->{password.setTransformationMethod(checked?android.text.method.HideReturnsTransformationMethod.getInstance():android.text.method.PasswordTransformationMethod.getInstance());password.setSelection(password.length());});box.addView(reveal);
  LinearLayout passwordActions=new LinearLayout(this);Button remember=new Button(this);remember.setText("保存密码");CuteUi.style(remember,CuteUi.MINT,true);passwordActions.addView(remember,new LinearLayout.LayoutParams(0,CuteUi.dp(this,48),1));Button forget=new Button(this);forget.setText("清除已保存密码");CuteUi.style(forget,CuteUi.PINK,true);passwordActions.addView(forget,new LinearLayout.LayoutParams(0,CuteUi.dp(this,48),1));box.addView(passwordActions);
  remember.setOnClickListener(v->{try{String destination=Endpoint.host(address.getText().toString()),name=user.getText().toString(),secret=password.getText().toString();if(name.isEmpty()||secret.isEmpty())throw new IllegalArgumentException("请先填写用户名和密码");passwordStore.save(destination,name,secret);saved.edit().putString("host",destination).putString("username",name).apply();status.setText("密码已在本机加密保存，下次自动填入。");}catch(Exception e){status.setText("保存失败："+message(e));}});
  forget.setOnClickListener(v->{try{passwordStore.clear();password.setText("");status.setText("已清除保存的密码。");}catch(Exception e){status.setText("清除失败："+message(e));}});
  android.text.TextWatcher accountChanged=new android.text.TextWatcher(){public void beforeTextChanged(CharSequence s,int start,int count,int after){}public void onTextChanged(CharSequence s,int start,int before,int count){restorePassword();}public void afterTextChanged(android.text.Editable s){}};address.addTextChangedListener(accountChanged);user.addTextChangedListener(accountChanged);
  TextView qualityLabel=new TextView(this);qualityLabel.setText("清晰度（下次连接生效）");box.addView(qualityLabel);
  Spinner quality=new Spinner(this);String[] labels={"432P · 流畅画质 · 432 × 960","540P · DVD清晰度 · 540 × 1200","720P · 主流高清 · 720 × 1600","1080P · 蓝光 · 1080 × 2400"};int[] sizes={960,1200,1600,2400};
  ArrayAdapter<String> choices=new ArrayAdapter<>(this,android.R.layout.simple_spinner_item,labels);choices.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);quality.setAdapter(choices);
  int[] legacySizes={960,1600,2400};int remembered=saved.getInt("quality_max_size",legacySizes[Math.max(0,Math.min(2,saved.getInt("quality",1)))]);int selected=2;for(int i=0;i<sizes.length;i++)if(sizes[i]==remembered)selected=i;quality.setSelection(selected);box.addView(quality);
  TextView modeLabel=new TextView(this);modeLabel.setText("编码模式（下次连接生效）");box.addView(modeLabel);Spinner mode=new Spinner(this);String[] modes={"CBR · 固定码率","VBR · 可变码率"};ArrayAdapter<String> modeChoices=new ArrayAdapter<>(this,android.R.layout.simple_spinner_item,modes);modeChoices.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);mode.setAdapter(modeChoices);mode.setSelection(saved.getString("bitrate_mode","CBR").equals("VBR")?1:0);box.addView(mode);TextView modeHint=new TextView(this);modeHint.setText("CBR 保持固定目标码率；VBR 随画面复杂度调整。当前模拟器不支持 AVBR，不能选择。两种模式都使用流畅播放缓冲。");modeHint.setTextSize(12);box.addView(modeHint);
  TextView rateLabel=new TextView(this);rateLabel.setText("目标码率（Mbps，下次连接生效）");box.addView(rateLabel);
  Spinner rate=new Spinner(this);String[] rateLabels={"2.5 Mbps · 省流畅用","4 Mbps · 720p 推荐","6 Mbps · 720p 更清晰","8 Mbps · 1080p 推荐","12 Mbps · 编码器上限","自定义"};int[] rateValues={2500000,4000000,6000000,8000000,12000000};ArrayAdapter<String> rateChoices=new ArrayAdapter<>(this,android.R.layout.simple_spinner_item,rateLabels);rateChoices.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);rate.setAdapter(rateChoices);box.addView(rate);
  int rememberedRate=saved.getInt("video_bit_rate",2500000),rateSelected=5;for(int i=0;i<rateValues.length;i++)if(rememberedRate==rateValues[i])rateSelected=i;
  EditText customRate=field(box,"自定义 0.5–12 Mbps，例如 5.5",java.math.BigDecimal.valueOf(rememberedRate,6).stripTrailingZeros().toPlainString());customRate.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL);rate.setSelection(rateSelected);customRate.setVisibility(rateSelected==5?View.VISIBLE:View.GONE);
  rate.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener(){public void onItemSelected(AdapterView<?> parent,View view,int position,long id){customRate.setVisibility(position==5?View.VISIBLE:View.GONE);}public void onNothingSelected(AdapterView<?> parent){}});
  TextView rateHint=new TextView(this);rateHint.setText("540p 推荐 2–3，720p 推荐 4–6，1080p 推荐 8–12 Mbps。更高码率提升清晰度，也可能增加延迟；它不会提高帧率。当前编码器最高 12 Mbps。画面流畅优先，播放缓冲约 80 ms。");rateHint.setTextSize(12);box.addView(rateHint);
  Button start=new Button(this);start.setText("连接虚拟安卓");CuteUi.style(start,CuteUi.MINT,false);box.addView(start,new LinearLayout.LayoutParams(-1,CuteUi.dp(this,60)));status=new TextView(this);status.setText("默认通过 NPS 公网连接。密码需点“保存密码”后才会加密保存。");box.addView(status);
  start.setOnClickListener(v->{
   try{host=Endpoint.host(address.getText().toString());}catch(IllegalArgumentException e){status.setText(e.getMessage());return;}
   try{bitRate=rate.getSelectedItemPosition()<5?rateValues[rate.getSelectedItemPosition()]:Bitrate.parseMbps(customRate.getText().toString());}catch(IllegalArgumentException e){status.setText(e.getMessage());return;}
   address.setText(host);maxSize=sizes[quality.getSelectedItemPosition()];bitrateMode=mode.getSelectedItemPosition()==1?"VBR":"CBR";
   saved.edit().putString("host",host).putString("username",user.getText().toString()).putInt("quality_max_size",maxSize).putInt("video_bit_rate",bitRate).putString("bitrate_mode",bitrateMode).apply();
   auth="Basic "+Base64.encodeToString((user.getText()+":"+password.getText()).getBytes(StandardCharsets.UTF_8),2);start.setEnabled(false);status.setText("连接中…");
   new Thread(()->{try{initTLS();String id=session();runOnUiThread(()->{password.setText("");show(id);});}catch(Exception e){auth=null;runOnUiThread(()->{status.setText("连接失败："+message(e));start.setEnabled(true);});}},"login").start();
  });
  Button filesButton=new Button(this);filesButton.setText("照片 · 视频互传");CuteUi.style(filesButton,CuteUi.MINT,false);box.addView(filesButton,new LinearLayout.LayoutParams(-1,CuteUi.dp(this,56)));
  filesButton.setOnClickListener(v->{try{host=Endpoint.host(address.getText().toString());initTLS();auth="Basic "+Base64.encodeToString((user.getText()+":"+password.getText()).getBytes(StandardCharsets.UTF_8),2);saved.edit().putString("host",host).putString("username",user.getText().toString()).apply();password.setText("");openFiles();}catch(Exception e){status.setText(message(e));}});
  ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);scroll.addView(box);
  scroll.setOnApplyWindowInsetsListener((v,insets)->{android.graphics.Insets i=insets.getInsets(WindowInsets.Type.systemBars());v.setPadding(i.left,i.top,i.right,i.bottom);return insets;});setContentView(scroll);restorePassword();updater.check(false);
 }
 void restorePassword(){try{password.setText(passwordStore.load(Endpoint.host(address.getText().toString()),user.getText().toString()));}catch(IllegalArgumentException e){password.setText("");}catch(Exception e){password.setText("");if(status!=null)status.setText("已保存的密码无法读取，请重新输入并保存。");}}
 EditText field(LinearLayout b,String hint,String value){EditText f=new EditText(this);f.setSingleLine();f.setTextColor(CuteUi.INK);f.setHintTextColor(0xff719095);f.setBackgroundTintList(android.content.res.ColorStateList.valueOf(0xffaacfc5));f.setHint(hint);f.setText(value);b.addView(f);return f;}
 static String message(Exception e){return e.getMessage()==null?e.getClass().getSimpleName():e.getMessage();}
 void initTLS()throws Exception{KeyStore ks=KeyStore.getInstance(KeyStore.getDefaultType());ks.load(null,null);fingerprints.clear();int[] resources={R.raw.server_cert,R.raw.server_cert_m5};for(int i=0;i<resources.length;i++){X509Certificate cert;try(InputStream in=getResources().openRawResource(resources[i])){cert=(X509Certificate)CertificateFactory.getInstance("X.509").generateCertificate(in);}fingerprints.add(MessageDigest.getInstance("SHA-256").digest(cert.getEncoded()));ks.setCertificateEntry("mac"+i,cert);}TrustManagerFactory tm=TrustManagerFactory.getInstance(TrustManagerFactory.getDefaultAlgorithm());tm.init(ks);tls=SSLContext.getInstance("TLS");tls.init(null,tm.getTrustManagers(),null);}
 SSLSocket connect()throws Exception{SSLSocket s=(SSLSocket)tls.getSocketFactory().createSocket();s.connect(new java.net.InetSocketAddress(host,15556),7000);s.setSoTimeout(15000);s.setTcpNoDelay(true);s.startHandshake();byte[] actual=MessageDigest.getInstance("SHA-256").digest(s.getSession().getPeerCertificates()[0].getEncoded());boolean trusted=false;for(byte[] pin:fingerprints)trusted|=MessageDigest.isEqual(actual,pin);if(!trusted){s.close();throw new IOException("Mac 证书不匹配");}sockets.add(s);return s;}
 int header(InputStream in)throws Exception{ByteArrayOutputStream b=new ByteArrayOutputStream();int state=0;while(b.size()<16384){int c=in.read();if(c<0)throw new EOFException();b.write(c);if(state==0&&c==13)state=1;else if(state==1&&c==10)state=2;else if(state==2&&c==13)state=3;else if(state==3&&c==10)break;else state=0;}return Integer.parseInt(b.toString("US-ASCII").split("\\r\\n")[0].split(" ")[1]);}
 String session()throws Exception{SSLSocket s=connect();s.setSoTimeout(150000);byte[] settings=("{\"max_size\":"+maxSize+",\"video_bit_rate\":"+bitRate+",\"bitrate_mode\":\""+bitrateMode+"\"}").getBytes(StandardCharsets.UTF_8);OutputStream out=s.getOutputStream();out.write(("POST /session HTTP/1.1\r\nHost: "+host+"\r\nAuthorization: "+auth+"\r\nContent-Type: application/json\r\nContent-Length: "+settings.length+"\r\nConnection: close\r\n\r\n").getBytes(StandardCharsets.US_ASCII));out.write(settings);InputStream in=s.getInputStream();int code=header(in);if(code!=200){s.close();throw new IOException(code==401?"登录被拒绝：请点“显示密码”核对用户名和特殊符号":code==429?"登录尝试过多，请稍后重试":"服务启动失败（"+code+"）");}ByteArrayOutputStream b=new ByteArrayOutputStream();byte[] buf=new byte[1024];int n;while((n=in.read(buf))>0)b.write(buf,0,n);s.close();sockets.remove(s);return new JSONObject(b.toString("UTF-8")).getString("session");}
 SSLSocket stream(String id,String role)throws Exception{SSLSocket s=connect();s.getOutputStream().write(("CONNECT /stream/"+id+"/"+role+" HTTP/1.1\r\nHost: "+host+"\r\nAuthorization: "+auth+"\r\n\r\n").getBytes(StandardCharsets.US_ASCII));if(header(s.getInputStream())!=200)throw new IOException("通道连接失败："+role);s.setSoTimeout(0);return s;}
 void show(String id){running=true;int gen=++generation;playback=new PlaybackClock();networkRttMs=-1;LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setOnApplyWindowInsetsListener((v,insets)->{android.graphics.Insets i=insets.getInsets(WindowInsets.Type.systemBars());v.setPadding(i.left,i.top,i.right,i.bottom);return insets;});canvas=new FrameLayout(this);canvas.setBackgroundColor(0xff000000);root.addView(canvas,new LinearLayout.LayoutParams(-1,0,1));screen=new SurfaceView(this);canvas.addView(screen,new FrameLayout.LayoutParams(-1,-1,17));screen.setOnTouchListener((v,e)->{if(e.getActionMasked()==MotionEvent.ACTION_MOVE){long now=SystemClock.uptimeMillis();if(now-lastMoveMs<16)return true;lastMoveMs=now;}MotionEvent copy=MotionEvent.obtain(e);input.execute(()->{touch(copy);copy.recycle();});return true;});int[] codes={4,3,187};LinearLayout bar=CuteUi.controls(this,j->{if(j<3)input.execute(()->key(codes[j]));else if(j==3)openFiles();else{stop();login();}});root.addView(bar);perf=new TextView(this);perf.setTextColor(0xffffffff);perf.setBackgroundColor(0x99000000);perf.setTextSize(11);perf.setPadding(8,4,8,4);canvas.addView(perf,new FrameLayout.LayoutParams(-2,-2,Gravity.TOP|Gravity.START));metricsVisible=getSharedPreferences("connection",0).getBoolean("metrics_visible",true);metricsToggle=new Button(this);CuteUi.style(metricsToggle,CuteUi.MINT,true);canvas.addView(metricsToggle,new FrameLayout.LayoutParams(CuteUi.dp(this,88),CuteUi.dp(this,48),Gravity.TOP|Gravity.END));metricsToggle.setOnClickListener(v->{metricsVisible=!metricsVisible;getSharedPreferences("connection",0).edit().putBoolean("metrics_visible",metricsVisible).apply();updateMetricsVisibility();});updateMetricsVisibility();setContentView(root);canvas.post(this::fit);receivedFrames.set(0);presentedFrames.set(0);stats(gen);new Thread(()->measureRtt(gen),"network-rtt").start();new Thread(()->{try{SSLSocket vs=stream(id,"video"),as=stream(id,"audio"),cs=stream(id,"control");control=new DataOutputStream(new BufferedOutputStream(cs.getOutputStream(),8192));new Thread(()->readAudio(as,gen),"audio").start();new Thread(()->{try{byte[] b=new byte[2048];while(running&&gen==generation&&cs.getInputStream().read(b)>=0){}}catch(Exception ignored){}},"control-replies").start();readVideo(vs,gen);}catch(Exception e){if(running&&gen==generation)fail(e);}},"video").start();}

 static boolean virtualCodec(String name){return name.startsWith("c2.goldfish.")||name.startsWith("OMX.google.goldfish.");}
 MediaCodec fastDecoder(MediaFormat format)throws Exception{
  MediaCodecInfo chosen=null;int score=-1;
  for(MediaCodecInfo info:new MediaCodecList(MediaCodecList.REGULAR_CODECS).getCodecInfos()){
   if(info.isEncoder()||info.isAlias()||!info.isHardwareAccelerated()||virtualCodec(info.getName()))continue;
   for(String type:info.getSupportedTypes())if(type.equalsIgnoreCase("video/avc")){
    try{MediaCodecInfo.CodecCapabilities cap=info.getCapabilitiesForType(type);MediaFormat basic=MediaFormat.createVideoFormat("video/avc",width,height);
     if(!cap.isFormatSupported(basic)||cap.isFeatureRequired(MediaCodecInfo.CodecCapabilities.FEATURE_SecurePlayback)||cap.isFeatureRequired(MediaCodecInfo.CodecCapabilities.FEATURE_TunneledPlayback))continue;
     int candidate=cap.isFeatureSupported(MediaCodecInfo.CodecCapabilities.FEATURE_LowLatency)?2:1;if(candidate>score){score=candidate;chosen=info;}
    }catch(Exception ignored){}
   }
  }
  // Emulator host codecs may advertise hardware support but fail on the first frame.
  // Physical-phone hardware codecs retain priority; use a real software codec only as fallback.
  if(chosen==null)for(MediaCodecInfo info:new MediaCodecList(MediaCodecList.REGULAR_CODECS).getCodecInfos()){
   if(info.isEncoder()||info.isAlias()||!info.isSoftwareOnly())continue;
   for(String type:info.getSupportedTypes())if(type.equalsIgnoreCase("video/avc")){chosen=info;break;}
   if(chosen!=null)break;
  }
  MediaCodec decoder=chosen==null?MediaCodec.createDecoderByType("video/avc"):MediaCodec.createByCodecName(chosen.getName());hardwareVideo=decoder.getCodecInfo().isHardwareAccelerated();return decoder;
 }
 void stats(int gen){final long[] previous={System.nanoTime(),0,0};ui.postDelayed(new Runnable(){public void run(){if(!running||gen!=generation)return;long now=System.nanoTime(),rx=receivedFrames.get(),shown=presentedFrames.get();double dt=(now-previous[0])/1e9;perf.setText(String.format(java.util.Locale.ROOT,"接收 %.0f · 显示 %.0f FPS\n%d×%d · %s\n网络往返 %s ms · 缓冲 80 ms · %s",(rx-previous[1])/dt,(shown-previous[2])/dt,width,height,hardwareVideo?"硬件解码":"软件解码",networkRttMs<0?"—":Long.toString(networkRttMs),bitrateMode));previous[0]=now;previous[1]=rx;previous[2]=shown;ui.postDelayed(this,1000);}},1000);}

 void updateMetricsVisibility(){perf.setVisibility(metricsVisible?View.VISIBLE:View.GONE);metricsToggle.setText(metricsVisible?"隐藏指标":"显示指标");}
 void fit(){if(canvas==null)return;int w=canvas.getWidth(),h=canvas.getHeight();if(w==0||h==0)return;float s=Math.min((float)w/width,(float)h/height);screen.setLayoutParams(new FrameLayout.LayoutParams(Math.round(width*s),Math.round(height*s),17));}
 void configure(int w,int h,int gen)throws Exception{width=w;height=h;runOnUiThread(this::fit);for(int i=0;i<100&&running&&!screen.getHolder().getSurface().isValid();i++)Thread.sleep(20);MediaCodec old=video;video=null;if(old!=null){old.stop();old.release();}MediaFormat f=MediaFormat.createVideoFormat("video/avc",w,h);f.setInteger(MediaFormat.KEY_LOW_LATENCY,1);MediaCodec d=fastDecoder(f);Surface surface=screen.getHolder().getSurface();try{surface.setFrameRate(60,Surface.FRAME_RATE_COMPATIBILITY_FIXED_SOURCE);}catch(IllegalStateException ignored){}d.configure(f,surface,null,0);d.start();video=d;d.setOnFrameRenderedListener((codec,pts,ns)->{if(running&&gen==generation&&video==d)presentedFrames.incrementAndGet();},new Handler(statsThread.getLooper()));PlaybackClock clock=playback;new Thread(()->{MediaCodec.BufferInfo info=new MediaCodec.BufferInfo();try{while(running&&gen==generation&&video==d){int index=d.dequeueOutputBuffer(info,10000);if(index>=0){long target=clock.deadline(info.presentationTimeUs);if(target<System.nanoTime()-40000000L){d.releaseOutputBuffer(index,false);continue;}while(running&&gen==generation&&video==d&&target-System.nanoTime()>20000000L)Thread.sleep(2);if(!running||gen!=generation||video!=d)break;d.releaseOutputBuffer(index,Math.max(System.nanoTime(),target));}}}catch(Exception e){if(running&&gen==generation&&video==d)fail(e);}},"video-render").start();}
 void readVideo(SSLSocket s,int gen)throws Exception{DataInputStream in=new DataInputStream(new BufferedInputStream(s.getInputStream(),65536));if(in.readInt()!=0x68323634)throw new IOException("不支持的视频编码");while(running&&gen==generation){int hi=in.readInt();if((hi&0x80000000)!=0){int w=in.readInt(),h=in.readInt();if(w<1||h<1||w>8192||h>8192)throw new IOException("无效画面尺寸");configure(w,h,gen);continue;}long pts=((long)hi<<32)|(in.readInt()&0xffffffffL);int size=in.readInt();if(size<0||size>8*1024*1024)throw new IOException("无效视频帧");byte[] b=new byte[size];in.readFully(b);if((pts&(1L<<62))==0){receivedFrames.incrementAndGet();playback.observe(pts&((1L<<61)-1),System.nanoTime());}MediaCodec d=video;if(d==null)throw new IOException("缺少画面尺寸");int index=-1;while(running&&gen==generation&&(index=d.dequeueInputBuffer(10000))<0){}if(index<0)break;ByteBuffer buffer=d.getInputBuffer(index);buffer.clear();buffer.put(b);d.queueInputBuffer(index,0,size,pts&((1L<<61)-1),(pts&(1L<<62))!=0?MediaCodec.BUFFER_FLAG_CODEC_CONFIG:0);}}
 void readAudio(SSLSocket s,int gen){try{DataInputStream in=new DataInputStream(new BufferedInputStream(s.getInputStream(),16384));int codec=in.readInt();if(codec==0||codec==1)return;if(codec!=0x00616163)throw new IOException("不支持的音频编码");while(running&&gen==generation){long pts=in.readLong();int size=in.readInt();if(size<0||size>1024*1024)throw new IOException("无效音频帧");byte[] data=new byte[size];in.readFully(data);if((pts&(1L<<62))!=0){MediaFormat f=MediaFormat.createAudioFormat("audio/mp4a-latm",48000,2);f.setByteBuffer("csd-0",ByteBuffer.wrap(data));MediaCodec d=MediaCodec.createDecoderByType("audio/mp4a-latm");d.configure(f,null,null,0);d.start();audio=d;int min=AudioTrack.getMinBufferSize(48000,12,2);track=new AudioTrack.Builder().setAudioFormat(new AudioFormat.Builder().setSampleRate(48000).setChannelMask(AudioFormat.CHANNEL_OUT_STEREO) .setEncoding(AudioFormat.ENCODING_PCM_16BIT).build()).setAudioAttributes(new AudioAttributes.Builder().setUsage(AudioAttributes.USAGE_MEDIA).setContentType(AudioAttributes.CONTENT_TYPE_MOVIE).build()).setTransferMode(AudioTrack.MODE_STREAM).setBufferSizeInBytes(Math.max(min,4096)).setPerformanceMode(AudioTrack.PERFORMANCE_MODE_LOW_LATENCY).build();track.play();new Thread(()->drainAudio(d,gen),"audio-render").start();continue;}playback.observe(pts&((1L<<61)-1),System.nanoTime());MediaCodec d=audio;if(d==null)continue;int index=-1;while(running&&gen==generation&&(index=d.dequeueInputBuffer(10000))<0){}if(index<0)break;ByteBuffer buf=d.getInputBuffer(index);buf.clear();buf.put(data);d.queueInputBuffer(index,0,size,pts&((1L<<61)-1),0);}}catch(Exception e){if(running&&gen==generation)runOnUiThread(()->Toast.makeText(this,"音频暂不可用："+message(e),Toast.LENGTH_LONG).show());}}
 void drainAudio(MediaCodec d,int gen){AudioTrack output=track;PlaybackClock clock=playback;long writtenFrames=0;try{MediaCodec.BufferInfo info=new MediaCodec.BufferInfo();while(running&&gen==generation&&audio==d){int index=d.dequeueOutputBuffer(info,10000);if(index>=0){ByteBuffer b=d.getOutputBuffer(index);b.position(info.offset);b.limit(info.offset+info.size);long target=clock.deadline(info.presentationTimeUs);while(running&&gen==generation&&audio==d){long queued=Math.max(0,writtenFrames-(output.getPlaybackHeadPosition()&0xffffffffL));long wait=target-System.nanoTime()-queued*1000000000L/48000;if(wait<=2000000L)break;Thread.sleep(Math.min(10,Math.max(1,wait/1000000L)));}while(b.hasRemaining()&&running&&gen==generation&&audio==d){int bytes=output.write(b,b.remaining(),AudioTrack.WRITE_BLOCKING);if(bytes<0)throw new IOException("音频输出失败");writtenFrames+=bytes/4;}d.releaseOutputBuffer(index,false);}}}catch(Exception ignored){}}
 void measureRtt(int gen){while(running&&gen==generation){SSLSocket socket=null;try{socket=connect();long start=System.nanoTime();socket.getOutputStream().write(("GET /ping HTTP/1.1\r\nHost: "+host+"\r\nConnection: close\r\n\r\n").getBytes(StandardCharsets.US_ASCII));if(header(socket.getInputStream())==200&&running&&gen==generation)networkRttMs=Math.max(1,(System.nanoTime()-start)/1000000L);else networkRttMs=-1;}catch(Exception ignored){if(gen==generation)networkRttMs=-1;}finally{if(socket!=null){sockets.remove(socket);try{socket.close();}catch(Exception ignored){}}}try{Thread.sleep(3000);}catch(InterruptedException e){return;}}}
 synchronized void touch(MotionEvent e){if(control==null||!running)return;try{int a=e.getActionMasked();if(a==2){for(int i=0;i<e.getPointerCount();i++)pointer(e,i,2);}else if(a==0||a==5)pointer(e,e.getActionIndex(),0);else if(a==1||a==6)pointer(e,e.getActionIndex(),1);else if(a==3){for(int i=0;i<e.getPointerCount();i++)pointer(e,i,1);}control.flush();}catch(Exception ex){fail(ex);}}
 void pointer(MotionEvent e,int i,int a)throws IOException{int x=Math.max(0,Math.min(width-1,Math.round(e.getX(i)*width/screen.getWidth()))),y=Math.max(0,Math.min(height-1,Math.round(e.getY(i)*height/screen.getHeight())));control.writeByte(2);control.writeByte(a);control.writeLong(e.getPointerId(i));control.writeInt(x);control.writeInt(y);control.writeShort(width);control.writeShort(height);control.writeShort(a==1?0:65535);control.writeInt(0);control.writeInt(0);}
 synchronized void key(int code){if(control==null)return;try{for(int a=0;a<2;a++){control.writeByte(0);control.writeByte(a);control.writeInt(code);control.writeInt(0);control.writeInt(0);}control.flush();}catch(Exception e){fail(e);}}
 void fail(Exception e){runOnUiThread(()->{if(!running)return;stop();login();status.setText("连接中断："+message(e));});}
 void stop(){running=false;generation++;control=null;auth=null;synchronized(sockets){for(SSLSocket s:sockets)try{s.close();}catch(Exception ignored){}sockets.clear();}MediaCodec v=video,a=audio;video=null;audio=null;for(MediaCodec d:new MediaCodec[]{v,a})if(d!=null)try{d.stop();d.release();}catch(Exception ignored){}if(track!=null){try{track.stop();track.release();}catch(Exception ignored){}track=null;}}
 void openFiles(){boolean resume=running;String credential=auth;stop();auth=credential;transfer=new MediaTransfer(this,()->{transfer=null;if(resume){new Thread(()->{try{String id=session();runOnUiThread(()->show(id));}catch(Exception e){runOnUiThread(()->{auth=null;login();status.setText("重新连接失败："+message(e));});}},"resume-after-files").start();}else{auth=null;login();}});}
 public void onActivityResult(int request,int code,android.content.Intent data){super.onActivityResult(request,code,data);if(transfer!=null)transfer.result(request,code,data);}
 // API33+ is registered with the platform dispatcher above; this fallback serves API30-32.
 @android.annotation.SuppressLint("GestureBackNavigation")
 public void onBackPressed(){handleBack();}
 void handleBack(){if(transfer!=null){transfer.back();return;}if(running)input.execute(()->key(4));else finish();}
 protected void onResume(){super.onResume();if(updater!=null)updater.resumeInstall();}
 protected void onDestroy(){if(transfer!=null)transfer.close();stop();input.shutdownNow();statsThread.quitSafely();super.onDestroy();}
}
